### PR TITLE
Run formatter, add some docs, and reorganize directory strucuture a bit

### PR DESCRIPTION
**Pull request by davidsantoso**
No functional changes (just yet!) in this commit. This is more to unify
some of the code formatting, reorganize the directory structure a bit,
and add some documentation on what each of the components are doing or
are used for since there are quite a few moving pieces and in some
places we rely on brod. A couple of structural changes are already planned
but this should break up the commits a bit.

---

@objectuser @duff 

I have a couple other "structural"/functional changes coming, but I thought
I'd start with this since I didn't want to have a bunch of those mixed in with
a formatter run and such. I'm thinking of this as a foundation to some larger
changes especially since there are things I think we can take advantage of in
newer versions of brod. As it stands, things are breaking past brod 3.3.5?

This looks like _a lot_ of changes because I ran the  formatter and added a fair
amount of docs so someone new coming in can hopefully get up and running
quickly. Also, the directory structure is just a little different, the biggest change
being renaming the top level `group_member` directory to `consumer_group`.
That _seemed_ more descriptive to me since "group member" sounds like one
thing but there's actually a lot going on to support consuming via a consumer
group. Anyway, would appreciate your thoughts.

New directory structure:
```
kaffe
├── config
│   ├── consumer.ex
│   └── producer.ex
├── config.ex
├── consumer.ex
├── consumer_group
│   ├── group_manager.ex
│   ├── group_member_supervisor.ex
│   ├── subscriber
│   │   ├── group_member.ex
│   │   └── subscriber.ex
│   └── worker
│       ├── worker.ex
│       ├── worker_manager.ex
│       └── worker_supervisor.ex
├── partition_selector.ex
└── producer.ex
```

### CODE REVIEW

**Comment by objectuser** [comment]
Good first step. I'm excited to see where this goes! I think the structure is a good logical layout.

Wondering if we should consider this the start of Kaffe 2.0. That would allow breaking changes in terms of the config, the producer and other things we've discussed.

Did Git really not handle the moves on some files? Wondering if that's just GitHub or if we'll really lose some history there.

**Comment by davidsantoso** [comment]
> Did Git really not handle the moves on some files?

Just looked in my zsh history and it looks like I ran an `mv` instead of a `git mv` ☹️ Going to have to think for a minute on how to redo the branch so we don't lose all of that history. May have to manually redo things. Updated PR coming soon(ish).

**Comment by davidsantoso** [comment]
So, I just pushed a [new branch](https://github.com/spreedly/kaffe/commit/2624995ca34f7c7e0ae24d34a237d0202fa985b9) that is only moving the files under a new directory using `git mv` and here in GitHub it's not showing any history for the file. But, using `git blame` on the command line, I can still see the history. So I guess we're not really losing it but we are losing it in the GitHub UI. Which is unfortunate.

**Comment by davidsantoso** [comment]
Closing in favor of #77

**Pull request closed without merging**
