### PR TITLE
Fix undefined function exponential_backoff not found

### PR DESCRIPTION
**Pull request by redmaner**
This fixes issue #106. It's a relatively simple change. Also see the retry docs that mention this [here](https://github.com/safwank/ElixirRetry#installation)

### CODE REVIEW

**Comment by redmaner** [comment]
@objectuser can you have a look at this?

**Comment by objectuser** [comment]
I'd say it looks legit, very reasonable. However, I'm not really a maintainer of the repo any longer, so can't merge it in. @fatcatt316?

**Comment by fatcatt316** [comment]
@objectuser I'll see what I can see either today or next week about this :salute:

**Review by schwarzgeist — APPROVED** [review]
Given previous approval by @objectuser, and after getting caught up with the issue/docs you provided (thank you for that), I also approve of this.

I hope this alleviates the issue(s) being seen. I'll be around to keep an eye on things if initial changes are needed.

**Comment by redmaner** [comment]
@schwarzgeist @fatcatt316 can the library be updated on hex as well?

**Comment by fatcatt316** [comment]
@redmaner Consider it done! It's been published to https://hex.pm/packages/kaffe/1.20.0

Thanks for submitting the fix.

**Pull request merged**
