### PR TITLE
Add a max_messages configuration option to the batched consumer.

### PR DESCRIPTION
**Pull request by cdegroot**
See the README change - with this, you can restrict batch sizes sent to
the callback keeping callbacks a bit simpler.

This is early day - I wanted the PR open to get some feedback, but still need to test this in a couple of our own services.

### CODE REVIEW

**Comment by objectuser** [comment]
@cdegroot Interesting idea! Having things in terms of messages has always made more sense to me than in bytes, though bytes does make memory consumption more predictable.

So there are two features of this PR:

1. Batching the messages delivered to the message handler in terms of `max_messages`
2. Ack'ing the messages after each batch

There is some complexity introduced by having a second (somewhat parallel) mechanism to control messages delivered to the handler.

It seems like the first is easy to implement in the handler with something like `Enum.chunk/2`. Do I understand that correctly? We could write in a message handler:

```
messages
|> Enum.chunk(max_messages)
|> Enum.each(fn (message_batch) ->
  for message <- message_batch do
    process_message(message)
  end
end)
```

The second can't be controlled by the message handler, so definitely interesting. Are you especially concerned with work lost on these intermediate batches? Would it be as effective to control that by reducing the value of `max_bytes`?

Definitely interested in hearing more of your thoughts on this and understanding your use cases. 👍

**Comment by cdegroot** [comment]
It's still a WIP (and why do i keep forgetting about `chunk`? This is the second time this happened to me. I'll fix the code) but yes, basically the partial acks are useful and not otherwise doable.

**Comment by cdegroot** [comment]
(chunk doesn't do what you want, I tried it ;-)). 

Anyway, what I feared happens, seems to happen - the ack is a trigger for Brod to fetch and send a new batch. I'm retracting the PR for now until I have time to do a deep-dive; I still think that the functionality can be useful to throttle work to reasonable levels in large backlog cases.

**Comment by objectuser** [comment]
@cdegroot I'd be interested in what you found on `chunk`! 

I will note that there are two different "acks" that Kaffe does. Look [here](https://github.com/spreedly/kaffe/blob/master/lib/kaffe/group_member/subscriber/subscriber.ex#L112). We could potentially separate the first from the second.

That said, I wonder if there are any advantages to chunking a set of messages vs. just setting the `max_bytes` parameter to something smaller.

**Comment by cdegroot** [comment]
```elixir
iex(1)> Enum.chunk(1..10, 20)
[]
iex(2)> Enum.chunk(1..10, 7)
[[1, 2, 3, 4, 5, 6, 7]]
```
I would expect `[[1..10]]` and `[[1..7],[8..10]]` to be the respective outcomes. 

Use case: we have a consumer that reads two topics which have wildly varying messages w.r.t. size. It reads messages and stashes them in S3. In the steady state, two instances can easily keep up; however, when there's a lot of lag each consumer gets a ton of in-flight messages fed - batches will typically be in the hundreds of messages, times 64 partitions for each consumer. That's just more in-flight processing than you want. 

`max_bytes` is useless if you don't have a standard message size (we got from regular low-kB to multi-MB) because Brod will tune it up when needed to fetch large messages, then slowly decrease it again - effectively, if you have large messages often enough then Brod will keep the actual `max_bytes` high enough so that your batches will be large and you need to start applying all sorts of hacks to reduce that when there's a backlog. 

This PR was a quick test, but I think the proper solution would be a GenStage compatible pipeline (the people over at `kafka_ex` are working on that, AFAIK). Maybe for some later time when I have some spare cycles to dive into this problem :-)

**Comment by objectuser** [comment]
Ah, need more parameters!

```
Enum.chunk(10000..10010, 7, 7, [])
[[10000, 10001, 10002, 10003, 10004, 10005, 10006],
 [10007, 10008, 10009, 10010]]
```

@cdegroot We've been talking internally about using GenStage for quite some time. I keep thinking it would be interesting to prototype it, but couldn't think of a use case in which it would be "better". I think you have one!

BTW, have you tried `kafka_ex`? We weren't able to use it at Spreedly because it wasn't ready at the time, but I wonder how it currently compares to Kaffe/Brod, especially in terms of performance and scalability.

**Comment by cdegroot** [comment]
Yeah, maybe I should read the docs ;-). Anyway, we started with kafka_ex, as we were only producing. When moving to the consumer site, kafka_ex did not have any support for the 0.9 style consumer stuff, so we swapped to Brod and later added Kaffe because it's simple and it works. In the meantime, kafka_ex has added most 0.10 stuff and is working on GenStage, so in terms of functionality they seem to have the lead at the moment; however, in terms of performance I'm not so sure - I like the design of Brod a bit more and it has some quite advanced functions like the auto-scaling of `max_bytes`. YMMV and "test your use case" apply, I think (and "why the <beep> is such a small community wasting time on two drivers?!?"). 

In terms of GenStage, I think that it's conceptually more correct to always pull data, regardless of your use case. But that's ol' opinionated me.

**Comment by objectuser** [comment]
Thanks for the feedback!

**Pull request closed without merging**
