### PR TITLE
Adding runtime-configuration instructions

### PR DESCRIPTION
**Pull request by rawkode**
As suggested by @sdball in #31 

If you had something else in mind, please just let me know.

Thanks

### CODE REVIEW

**Comment by rawkode** [comment]
Will I just close this, @objectuser ?

**Comment by objectuser** [comment]
@rawkode Sorry I had not taking the time to review your PR.

Because we don't use Weave at Spreedly I think the documentation would get out of date and ultimately be confusing. I wonder if a better approach would just be to reference Weave in the configuration section instead of providing an example.

What do you think?

**Comment by rawkode** [comment]
@objectuser It probably makes sense for Kaffe to be agnostic to which JIT configuration loader is used, as there are a few.

There was one issue about this and I commented with `:weave`. Lets close this for now and if someone else has similar woes, we can maybe address it again then :+1:

**Comment by objectuser** [comment]
@rawkode Sounds good, thanks.

**Pull request closed without merging**
