### PR TITLE
support for dynamically subscribing to new topics after start

### PR DESCRIPTION
**Pull request by dams**
code is straightforward. I'm using this to pilot what my application is subscribed to. Feedback welcome

### CODE REVIEW

**Comment by dams** [comment]
see the counterpart: #59

**Comment by dams** [comment]
ping ?

**Comment by dams** [comment]
Any progress ?

**Comment by objectuser** [comment]
@dams I merged this in. I refactored a few things. LMK if anything isn't what you'd expect.

I'm going to work the unsubscribe next.

**Pull request closed without merging**
