### PR TITLE
Add config settings for all Brod producer options

### PR DESCRIPTION
**Pull request by cdegroot**
We would like to enable compression, but other options may be useful as well - this patch contains the current full list.

### CODE REVIEW

**Comment by objectuser** [comment]
@cdegroot This is a great addition, thank you!

If you'll squash the commits I'll merge it in.

**Comment by cdegroot** [comment]
I can certainly do that, but isn't that what the "Squash and Merge" button on a PR is for? ;-)

**Comment by objectuser** [comment]
We tend not to use the buttons. 🙅‍♂️  😉

**Comment by objectuser** [comment]
@cdegroot I learned something about squashing commits and still doing a FF merge. If you've not done anything on this yet, I'm happy to squash/merge the PR in myself.

Thanks!

**Comment by cdegroot** [comment]
Don't worry - I'm lazy so I wanted to see how your button exploration went ;-)

**Comment by objectuser** [comment]
Ha! No buttons! 🚫

**Comment by objectuser** [comment]
Merged.

**Pull request closed without merging**
