### PR TITLE
Fixes https://github.com/spreedly/kaffe/issues/84

### PR DESCRIPTION
**Pull request by andyleclair**
Hi!

This PR does a few things:

First: ~bump the `brod` version~ *Edit:* turns out that wasn't needed!
Second: run `mix format`
Third: add support for `ssl: true` in producer/consumer configs

This will allow clients to connect to Confluent hosted Kafka!

### CODE REVIEW

**Comment by objectuser** [comment]
@andyleclair Thanks very much!

Previously we had compatibility issues with newer versions of Brod. Would apps using Kaffe have to use your README update?

```
        endpoints: [{"kafka", 9092}], # that's [{"hostname", kafka_port}]
```

**Comment by andyleclair** [comment]
Honestly, I haven't tried it! This was just the first thing I managed to get to work. I can for sure give it a go

**Comment by andyleclair** [comment]
@objectuser I've reverted the `brod` dependency change and it works just as well! Turns out the only bit that was actually needed was to add support for SASL over SSL!

I can revert the formatting changes also, if you want, that's just automatically run by my editor.

**Comment by objectuser** [comment]
@andyleclair Thanks very much! I'll take a look.

**Comment by objectuser** [comment]
@andyleclair Do the unit tests pass for you?

**Comment by andyleclair** [comment]
@objectuser I just pushed a new commit, and now they do! I also added new tests for the ssl config

**Comment by objectuser** [comment]
Will try to get back to this soon.

**Comment by andyleclair** [comment]
@objectuser any updates?

**Comment by objectuser** [comment]
@andyleclair I've not been able to get back to this yet, managing other priorities. I am hoping to get back this week still!

**Pull request closed without merging**
